<?php
get_header();
get_template_part('elements/banner');
get_template_part('elements/features');
get_template_part('elements/ChooseUs');
get_template_part('elements/Services');
get_template_part('elements/Process');
get_template_part('elements/Studies');
get_template_part('elements/Clients');
get_template_part('elements/Pricing');
get_template_part('elements/Testimonials');
get_template_part('elements/blog');
get_footer();